### ISSUE TITLE
[FR]: Support for multiple schemas?

### ISSUE THREAD

**Issue by mahyarmirrashed** [cenk1cenk2/schema-companion.nvim#16]
Hey! Was doing some k8s development, and was doing something like this:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  ...
spec:
  ...
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  ...
spec:
  ...
```

But it doesn't autocomplete for that second section. It keeps trying to autocomplete for a Deployment.

Have you encountered this? Do you know if YamlLS supports having multiple schemas in a single file? If so, it would be great to have that working here :)
